vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        douane:
            uri_prefix: /images/douane
            upload_destination: '%kernel.project_dir%/public/images/douane'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer